### ISSUE TITLE
Unable to set record syntax on resultset.

### ISSUE THREAD

**Issue by drigolin** [poying/node-zoom#5]
Setting result set syntax on resultset causes coredump

**Comment by drigolin** [comment]
resultset.option('preferredRecordSyntax','UNIMARC');

**Comment by poying** [comment]
I think I should rewrite this module. Maybe this weekend.

**Comment by drigolin** [comment]
Do you need any help? I can add the real case to do the test.

**Comment by poying** [comment]
@drigolin patch welcome :blush:
